config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#home'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create' 

  delete 'logout' => 'sessions#destroy'
  
  get "/auth/google_oauth2/callback" => 'sessions#google'

  resources :users do
    resources :songs, only: [:new, :create, :index]
    resources :setlists, only: [:index]
  end
  
  resources :setlists do
    resources :songs, only: [:new, :create, :index]
    resources :song_selections, only: [:new, :create, :index]
    resources :setlist_permissions, only: [:index, :new, :create, :edit]
  end

  resources :songs

  resources :setlist_permissions

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/setlist_permission.rb
class SetlistPermission < ApplicationRecord
  belongs_to :user
  belongs_to :setlist

  PERMISSIONS = {
    :destroy => 0,
    :edit => 10,
    :view => 100
  }
  
  def self.permissable(*args)
    args.each do |action|
      define_method "#{action}able?" do
        self.permission <= PERMISSIONS[action]
      end
    end
  end

  permissable :view, :edit, :destroy
  
  def user_email
    self.user.email
  end

  def permission_word
    PERMISSIONS.invert[self.permission]
  end
    

end

app/controllers/setlist_permissions_controller.rb
class SetlistPermissionsController < ApplicationController

  PERMISSIONS = {
    :destroy => 0,
    :edit => 10,
    :view => 100
  }

  def index
    if params[:setlist_id] && @setlist = Setlist.find_by_id(params[:setlist_id])
      @setlist_permissions = @setlist.setlist_permissions
    else
      @setlist_permissions = SetlistPermission.all
    end
  end

  def edit
    @setlist_permission = SetlistPermission.find(params[:id])
    @user = @setlist_permission.user_email
    @permissions = PERMISSIONS
  end

  def update
    @setlist_permission = SetlistPermission.find(params[:id])
    @setlist = Setlist.find_by(:id => params[:setlist_permission][:setlist_id])
    user = User.find_by(:email => params[:setlist_permission][:user_email])
    @setlist_permission.user_id = user.id
    @setlist_permission.permission = params[:setlist_permission][:permission]
    @setlist_permission.save
    redirect_to setlist_setlist_permissions_path(@setlist)
  end

  def new
    @setlist_permission = SetlistPermission.new
  end

  def create 
    @user = User.find_by(:email => params[:user_email])
    if !@user
      flash[:message] = "No such user exists."
      redirect_to new_setlist_setlist_permission_path(params[:setlist_id])
    else
      @setlist_permission = SetlistPermission.create(
        :user_id => @user.id, 
        :permission => params[:permission], 
        :setlist_id => params[:setlist_id]
        )
        redirect_to setlist_setlist_permissions_path(params[:setlist_id])
    end
  end

  def destroy
    @setlist_permission = SetlistPermission.find(params[:id])
    @setlist_id = @setlist_permission.setlist_id
    @setlist_permission.destroy
    flash[:message] = "Setlist permission deleted."
    redirect_to setlist_setlist_permissions_path(@setlist_id)
  end

  private
  def setlist_permission_params
    params.require(:setlist_permission).permit(
      :user_email,
      :permission,
      :setlist_id
    )
  end

end

app/helpers/setlist_permissions_helper.rb
module SetlistPermissionsHelper

  def show_hide_setlist_permission_edit(setlist_permission)
    if setlist_permission.user_id == Setlist.find_by_id(setlist_permission.setlist_id).user_id
      return "hide"
    else
      return ""
    end
  end

end

app/views/setlist_permissions/edit.html.erb
<br>
<h1>Edit Setlist Permission</h1>
<br>
<%= form_for([@setlist, @setlist_permission]) do |f| %>
    <label>User Email</label><br>
    <%= f.text_field :user_email %><br><br>
    <label>Permission Level</label><br>
    <%= f.select :permission, ([['view', 100], ['edit', 10], ['destroy', 0]]) %>
    <%= f.hidden_field :setlist_id %>
    <br>
    <br>
    <%= submit_tag "Submit" %>
    <% end %>

    <%= button_to "Delete Setlist Permission", setlist_permission_path(@setlist_permission), method: :delete, data: { confirm: "Would you like to delete this serlist permission? This cannot be undone." }, class:"delete-button" %>

app/views/setlist_permissions/index.html.erb
<br>
<h1>Setlist Permissions</h1>
<br>

  <% @setlist_permissions.each do |s| %>
    <%= s.user_email %> | <%= s.permission_word %> | <%= link_to "Edit this Permission", edit_setlist_setlist_permission_path(s.setlist_id, s), class:"#{show_hide_setlist_permission_edit s}" %>
    <br>
  <% end %>
<br>
  <%= link_to "Add new", new_setlist_setlist_permission_path(@setlist) %>

app/views/setlist_permissions/new.html.erb
<br><h1>Share Setlist</h1><br>
<%= form_tag setlist_setlist_permissions_path do %>
    <label>User Email</label><br>
    <%= text_field_tag :user_email %><br>
    <br>
    <label>Permission Level</label><br>
    <%= select_tag(:permission, options_for_select([['view', 100], ['edit', 10], ['destroy', 0]])) %>
    <br>
    <br>
    <%= submit_tag "Submit" %>
<% end %>