config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#home'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create' 

  delete 'logout' => 'sessions#destroy'
  
  get "/auth/google_oauth2/callback" => 'sessions#google'

  resources :users do
    resources :songs, only: [:new, :create, :index]
    resources :setlists, only: [:index]
  end
  
  resources :setlists do
    resources :songs, only: [:new, :create, :index]
    resources :song_selections, only: [:new, :create, :index]
    resources :setlist_permissions, only: [:index, :new, :create, :edit]
  end

  resources :songs

  resources :setlist_permissions

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/setlist.rb
class Setlist < ApplicationRecord
  has_many :song_selections, dependent: :destroy
  has_many :setlist_permissions, dependent: :destroy
  has_many :songs, through: :song_selections
  validates :title, presence: true

  accepts_nested_attributes_for :song_selections,
    reject_if: proc { |att| att['song_id'].blank? }

  def user_id
    sp = SetlistPermission.find_by(setlist_id: self.id, permission: 0)
    sp.user_id
  end

  def self.permissions_for(*args) 
    association = args[0]
    methods = args[1..-1]
    methods.each do |method_name|
      define_method "#{method_name}able_by?" do |user|
        assoc = self.send(association).find_by(:user_id => user.id)
        if !assoc
          return false
        else
          assoc.send("#{method_name}able?")
        end  
      end
    end
  end

  permissions_for :setlist_permissions, :edit, :view, :destroy
end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController

  def new
    @songs = current_user.songs.all.alpha
    @setlist = Setlist.new
    n = 1
    10.times do
      @setlist.song_selections.build(:song_number => n)
      n += 1
    end
  end
      
  def create
    @setlist = Setlist.new(setlist_params)
    if @setlist.save
      SetlistPermission.create(:user_id => current_user.id, :setlist_id => @setlist.id, :permission => 0)
      redirect_to setlist_path(@setlist)
    else
      @songs = current_user.songs.all.alpha
      render :new
    end
  end

  def edit
    @setlist = Setlist.find(params[:id])
    if !can_current_user?(:edit, @setlist)
      redirect_to root_path
    else
      @songs = ( @setlist.songs + current_user.songs.all ).uniq
      n = @setlist.song_selections.count + 1
      5.times do
        @setlist.song_selections.build(:song_number => n)
        n += 1
      end
    end
  end

  def update
    @setlist = Setlist.find(params[:id])
    @setlist.update(setlist_params)
    redirect_to setlist_path(@setlist)
  end

  def index
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
      @setlists = current_user.setlists.all
    else
      @setlists = Setlist.all
    end
  end

  def show
    @setlist = Setlist.find_by_id(params[:id])
    if !can_current_user?(:view, @setlist)
      redirect_to root_path
    end
  end

  def destroy
    setlist = Setlist.find(params[:id])
    setlist.destroy
    flash[:message] = "Setlist deleted."
    redirect_to user_path(current_user)
  end

  private

  def setlist_params
    params.require(:setlist).permit(
      :title, 
      :location, 
      :date,
      :id, 
      song_selections_attributes: [
        :song_id, 
        :setlist_id, 
        :song_number,
        :id
      ]
    )
  end

end

app/helpers/setlists_helper.rb
module SetlistsHelper


  def show_hide_edit(setlist)
    if can_current_user?(:edit, setlist)
      return ""
    else
      return "hide"
    end
  end

  def show_hide_delete(setlist)
    if can_current_user?(:destroy, setlist)
      return ""
    else
      return "-hide"
    end
  end
end

app/views/setlists/_form.html.erb
<%= form_for(@setlist) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <br>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <br>
    <br>
    <%= f.label :date %>
    <%= f.date_field :date %>
    <br>
    <br>
  
    <%= f.fields_for :song_selections do |ss| %>
      <%= ss.collection_select(:song_id, @songs, :id, :title, {:prompt => "Select Song"}) %><%= ss.hidden_field :song_number %><br>
    <% end %>
    <br>
    <%= f.submit "Submit" %>
  <% end %>

app/views/setlists/edit.html.erb
<br>
<h1>Edit Setlist</h1>
<br>
<%= link_to "Setlist permissions", setlist_setlist_permissions_path(@setlist) %> | <%= link_to "Create a new song to include in this setlist", new_setlist_song_path(@setlist) %>
<br>
<%= render partial: "layouts/errors", locals: {object: @setlist} %>
<br>
<%= render 'form' %>
<%= button_to "Delete Setlist", setlist_path(@setlist), method: :delete, data: { confirm: "Would you like to delete this setlist? This cannot be undone." }, class:"delete-button#{show_hide_delete @setlist}" %>

app/views/setlists/index.html.erb
<br>
<h1>Setlists</h1>
<br>

  <% @setlists.each do |s| %>
    <%= link_to s.title, setlist_path(s) %> | <%= s.date %>
    <br>
  <% end %>

app/views/setlists/new.html.erb
<br>
<h1>New Setlist</h1>
<br>
<%= render partial: "layouts/errors", locals: {object: @setlist} %>
<%= render 'form' %>

app/views/setlists/show.html.erb
<br>
<h1><%= @setlist.title %></h1>
<br>
<h2><%= @setlist.location %></h2>
<h2><%= @setlist.date %></h2>
<br>
<% @setlist.song_selections.each do |ss| %>
  <%= link_to ss.song_title, song_path(ss.song_id) %> | <%= ss.id %>
  <br>
<% end %>
<br>
<%= link_to "Edit Setlist", edit_setlist_path(@setlist), class:"#{show_hide_edit @setlist}" %>