config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#home'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create' 

  delete 'logout' => 'sessions#destroy'
  
  get "/auth/google_oauth2/callback" => 'sessions#google'

  resources :users do
    resources :songs, only: [:new, :create, :index]
    resources :setlists, only: [:index]
  end
  
  resources :setlists do
    resources :songs, only: [:new, :create, :index]
    resources :song_selections, only: [:new, :create, :index]
    resources :setlist_permissions, only: [:index, :new, :create, :edit]
  end

  resources :songs

  resources :setlist_permissions

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :setlist_permissions, dependent: :destroy
  has_many :setlists, through: :setlist_permissions, dependent: :destroy
  validates :display_name, presence: true
  validates :email, presence: true

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_songs_path(@user)
    else
      render :new
    end
  end

  def show
    redirect_if_not_logged_in
    @user = User.find_by_id(params[:id])
    @setlists = @user.setlists
    @songs = @user.songs
    redirect_to '/' if !@user
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_songs_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :display_name)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<br>
<h1>Settings</h1>
<br>
<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <br>
  <%= f.label :display_name %>
  <%= f.text_field :display_name %>
  <br>
  <br>
  <%= f.submit "Update" %>

<% end %>

app/views/users/index.html.erb
<h1>Users<h2>

  <% @users.each do |u| %>
    <%= link_to u.display_name, user_path(u) %> | <%= u.id %>
    <br>
  <% end %>

app/views/users/new.html.erb
<br>
<h1>Sign up</h1>

<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for(@user, url:'/signup') do |f| %>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %> 
  <br>
  <br>
  <%= f.label :display_name %>
  <%= f.text_field :display_name %>
  <br>
  <br>
  <br>
  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<br>
<h1>Welcome <%= @user.display_name %></h1>
<%= link_to "Settings", edit_user_path(@user) %>
<br>
<br>
<h2>Your Setlists</h2>
<% @setlists.each do |s| %>
    <%= link_to s.title, setlist_path(s) %> | <%= s.id %>
    <br>
  <% end %>
<br>
<h2>Your Songs</h2>
<% @songs.each do |s| %>
  <%= link_to s.title, song_path(s) %> | <%= s.id %>
  <br>
<% end %>