config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#home'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create' 

  delete 'logout' => 'sessions#destroy'
  
  get "/auth/google_oauth2/callback" => 'sessions#google'

  resources :users do
    resources :songs, only: [:new, :create, :index]
    resources :setlists, only: [:index]
  end
  
  resources :setlists do
    resources :songs, only: [:new, :create, :index]
    resources :song_selections, only: [:new, :create, :index]
    resources :setlist_permissions, only: [:index, :new, :create, :edit]
  end

  resources :songs

  resources :setlist_permissions

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <br>
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
    <br>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SongList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <div class="nav">
        <% if logged_in? %>
        
            <%= link_to "Create new setlist", new_setlist_path %> | 
            <%= link_to "Create new song", new_song_path %> | 
            <%= link_to "My songs", user_songs_path(current_user) %> | 
            <%= link_to "My setlists", user_setlists_path(current_user) %> | 
            <%= link_to "All public songs", songs_path %> | 
            <%= link_to "Settings", edit_user_path(current_user) %> | 
            <%= link_to "Log out", logout_path, method: :delete %> 
            <br><br>
        <% else %>     
            
            <%= link_to "Sign up", signup_path %> | 
            <%= link_to "Log in", login_path %> | 
            <%= link_to "Log in with Google", '/auth/google_oauth2', method: :post %> 
            <br><br>
        <% end %>
      </div>
      <div>
        <% if flash[:message] %>
          <br>
          <%= flash[:message] %>
          <br>
        <% end %>
      </div>
      <%= yield %>
      <footer class="branding">
        <small>&copy; 2021 <strong>Song List</strong></small>
      </footer>
    </div>
  </body>
</html>